### ISSUE TITLE
Numguess

### ISSUE THREAD

**Issue by zjping** [bonboru/NumGuess#1]
Your program runs successfully on my computer. Your indentation is good and you write a lot of notes. Your random numbers are different for each game. There is a little mistake, the value of B may not be increased when the same position numbers have the same value. All in all, you have done a good job.

**Comment by ghost** [comment]
The program runs well on my computer and there is no mistake during the test. The explains in the program are clear. I think you can chage the variable a and b into something like "bothCorrect" and "numCorrect", which can make the meannings easier to understand.

**Comment by leo77667** [comment]
The acknowledgement of  both capital and lowercase 'Y', contributes to its feasibility. And the check of equal suspected numbers  is great. Only the counting of 'B' seems not correct, for the wining condition is '3A0B', but not '3A3B' as your program indicates.

**Comment by luke-yao** [comment]
Good notes that makes it easier for me to understand at the first time.
And the structure is also great.
But should notice that the outcome of number of A & B has a mistake.
